name: "Build Lambda Layers"
description: "Builds and caches lambda layers"
    
runs:
  using: "composite"
  steps:
    - name: Check Lambda Layer Cache
      uses: actions/cache@v2
      id: cache-layers
      with:
        path: ./build/lambda_layers/
        key: ${{ runner.os }}-lambdalayer-${{ hashFiles('poetry.lock') }}
        restore-keys: ${{ runner.os }}-lambdalayer-${{ hashFiles('poetry.lock') }}
    - name: Build Lambda Layers
      run: poetry run task buildlayers
      shell: bash
      if: steps.cache-layers.outputs.cache-hit != 'true'