on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - run: which poetry
      - run: pipx list
      - run: ls -la /opt/pipx/venvs/poetry
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: 'poetry'
      - run: poetry install
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::905590892698:role/gha-oidc
          role-session-name: ${{ github.sha }}