on:
  push:
    branches:
      - main
env:
  poetry_version: "1.1.12"

jobs:
  build:
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS
        uses: ././github/actions/configure-aws
      - name: Bootstrap Poetry
        uses: ./.github/actions/bootstrap-poetry
      - name: Build Lambda Layers
        uses: ./.github/actions/lambda-layers
      
