on:
  push:
    branches:
      - main
env:
  poetry_version: "1.1.12"

jobs:
  bootstrap:
    runs-on: ubuntu-latest
    uses: chalupaul/heimdall/.github/workflows/poetry.yml@main
  build:
    needs: bootstrap
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Lambda Layer Cache
        uses: actions/cache@v2
        id: cache-layers
        with:
          path: ./build/lambda_layer
          key: ${{ runner.os }}-lambda-layer-${{ hashFiles('poetry.lock') }}
          restore-keys: ${{ runner.os }}-lambda-layer-${{ hashFiles('poetry.lock') }}
      - name: Build Lambda Layers
        run: poetry run task buildlayers
        if: steps.cache-layers.outputs.cache-hit != 'true'
      - run: ls -la ./build/lambda_layer
