on:
  workflow_call:

jobs:
  build:
    - uses: actions/cache@v2
        id: cache-poetry-venv
        with:
          path: |
            /opt/pipx/venvs/poetry/
            /opt/pipx_bin/poetry
          key: ${{ runner.os }}-poetry-${{ env.poetry_version }}
          restore-keys: |
            ${{ runner.os }}-poetry-${{ env.poetry_version }}
            ${{ runner.os}}-poetry-
    - run: pipx install poetry==${{ env.poetry_version }}
      if: steps.cache-poetry-venv.outputs.cache-hit != 'true'
    - uses: actions/setup-python@v3
      with:
        python-version: 3.9
        cache: 'poetry'
    - run: poetry install
    - uses: aws-actions/configure-aws-credentials@master
      with:
        aws-region: us-west-2
        role-to-assume: arn:aws:iam::905590892698:role/gha-oidc
        role-session-name: ${{ github.sha }}