name: Bootstrap Poetry

on:
  workflow_call:
    inputs:
      poetry-version:
        required: false
        type: string
        default: "1.1.12"

jobs:
  poetry_env:
    name: Bootstrap Poetry
    steps:
      - name: Poetry Cache
        uses: actions/cache@v2
        id: cache-poetry-venv
        with:
          path: |
            /opt/pipx/venvs/poetry/
            /opt/pipx_bin/poetry
          key: ${{ runner.os }}-poetry-${{ inputs.poetry-version }}
          restore-keys: ${{ runner.os}}-poetry-
      - name: Install Poetry
        run: pipx install poetry==${{ inputs.poetry_version }}
        if: steps.cache-poetry-venv.outputs.cache-hit != 'true'
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
          cache: 'poetry'
      - run: poetry install